import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  app: {
    minHeight: "100dvh",
    background: "var(--bg)",
    color: "var(--text)",
    fontFamily: "system-ui, -apple-system, Segoe UI, sans-serif",
    maxWidth: 480,
    margin: "0 auto",
  },
  header: {
    padding: "16px 20px 8px",
    position: "sticky",
    top: 0,
    background: "var(--bg)",
    zIndex: 10,
    borderBottom: "1px solid var(--border)",
  },
  title: {
    fontSize: "1.75rem",
    fontWeight: 700,
    margin: 0,
  },
  search: {
    width: "100%",
    padding: "12px 14px",
    fontSize: "1.05rem",
    borderRadius: 12,
    border: "1px solid var(--border)",
    marginTop: 12,
    boxSizing: "border-box",
  },
  chipRow: {
    display: "flex",
    gap: 8,
    overflowX: "auto",
    padding: "12px 20px",
    WebkitOverflowScrolling: "touch",
  },
  chip: {
    padding: "8px 14px",
    borderRadius: 999,
    border: "none",
    fontSize: "0.9rem",
    fontWeight: 600,
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  list: {
    padding: "0 12px 100px",
  },
  card: {
    background: "var(--card)",
    borderRadius: 16,
    padding: "16px 18px",
    marginBottom: 10,
    border: "1px solid var(--border)",
    cursor: "pointer",
    textAlign: "left",
    width: "100%",
  },
  cardTitle: {
    fontSize: "1.2rem",
    fontWeight: 700,
    margin: "0 0 6px",
  },
  fab: {
    position: "fixed",
    right: 20,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: "50%",
    background: "var(--accent)",
    color: "#fff",
    border: "none",
    fontSize: "1.75rem",
    boxShadow: "0 4px 16px rgba(0,0,0,0.2)",
    cursor: "pointer",
    zIndex: 20,
  },
  btnPrimary: {
    display: "block",
    width: "100%",
    padding: "16px",
    fontSize: "1.1rem",
    fontWeight: 700,
    borderRadius: 14,
    border: "none",
    background: "var(--accent)",
    color: "#fff",
    cursor: "pointer",
    marginBottom: 12,
  },
  btnSecondary: {
    display: "block",
    width: "100%",
    padding: "16px",
    fontSize: "1.1rem",
    fontWeight: 700,
    borderRadius: 14,
    border: "2px solid var(--accent)",
    background: "transparent",
    color: "var(--accent)",
    cursor: "pointer",
  },
  section: {
    padding: "16px 20px",
  },
  label: {
    fontSize: "0.85rem",
    fontWeight: 700,
    color: "var(--muted)",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    marginBottom: 8,
  },
  input: {
    width: "100%",
    padding: "12px",
    fontSize: "1.05rem",
    borderRadius: 10,
    border: "1px solid var(--border)",
    boxSizing: "border-box",
    marginBottom: 10,
  },
  toolbar: {
    display: "flex",
    gap: 8,
    padding: "12px 20px",
    borderBottom: "1px solid var(--border)",
    alignItems: "center",
  },
  backBtn: {
    background: "none",
    border: "none",
    fontSize: "1rem",
    color: "var(--accent)",
    cursor: "pointer",
    padding: "4px 0",
    fontWeight: 600,
  },
  segmented: {
    display: "flex",
    gap: 4,
    background: "var(--card)",
    borderRadius: 10,
    padding: 4,
    marginBottom: 16,
  },
  segment: {
    flex: 1,
    padding: "8px 4px",
    border: "none",
    borderRadius: 8,
    fontSize: "0.85rem",
    fontWeight: 600,
    cursor: "pointer",
    background: "transparent",
  },
  segmentActive: {
    background: "var(--accent)",
    color: "#fff",
  },
  empty: {
    textAlign: "center",
    padding: "48px 24px",
    color: "var(--muted)",
  },
};
